<div id="page-wrapper" style="min-height: 271px;">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Edición de Usuarios</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                           
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-lg-6">
                                    <form role="form" method="post" action="<?php echo BASE_URL ?>/backend/usuario/guardarUsuario"
                                          enctype="multipart/form-data">
                                        <input type="hidden" name="id" value="<?php echo $this->usuario->id?>">
                                        <div class="form-group">
                                            <label>Usuario</label>
                                            <input type='text' name='usuario' class="form-control"
                                                    value="<?php echo $this->usuario->usuario?>">
                                            
                                        </div>
                                        <div class="form-group">
                                            <label>Nombres</label>
                                            <input type='text' name='nombres' class="form-control"
                                                    value="<?php echo $this->usuario->nombres?>">
                                            
                                        </div>
                                        <div class="form-group">
                                            <label>Apellidos</label>
                                            <input type='text' name='apellidos' class="form-control"
                                                    value="<?php echo $this->usuario->apellidos?>">
                                            
                                        </div>
                                        <div class="form-group">
                                            <label>Email</label>
                                            <textarea name='email' class="form-control" rows="3"><?php echo $this->usuario->email?></textarea>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label>Teléfono</label>
                                            <input type='text' name='telefono' class="form-control"
                                                    value="<?php echo $this->usuario->telefono?>">
                                        </div>
                                        <div class="form-group">
                                            <label>Estado</label>
                                            <select class="form-control" name="estado">
                                                <option value="1" <?php if($this->usuario->estado == 1) echo "selected"; ?> > Activo </option>
                                                <option value="0" <?php if($this->usuario->estado == 0) echo "selected"; ?>>Inactivo</option>
                                            </select>
                                        </div>
                                        <button type="submit" class="btn btn-default">Submit Button</button>
                                        <button type="reset" class="btn btn-default">Reset Button</button>
                                    </form>
                                </div>
                                <!-- /.col-lg-6 (nested) -->
                                
                                <!-- /.col-lg-6 (nested) -->
                            </div>
                            <!-- /.row (nested) -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>