<div id="page-wrapper" style="min-height: 271px;">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Edición de Métodos de Pago</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                           
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-lg-6">
                                    <form role="form" method="post" action="<?php echo BASE_URL ?>/backend/metodopago/guardarMetodo">
                                        <input type="hidden" name="id" value="<?php echo $this->metodo->id?>">
                                        <div class="form-group">
                                            <label>Nombre</label>
                                            <input type='text' name='nombre' class="form-control"
                                                    value="<?php echo $this->metodo->nombre?>">
                                            
                                        </div>
                                        
                                        <div class="form-group">
                                            <label>Estado</label>
                                            <select class="form-control" name="estado">
                                                <option value="1" <?php if($this->metodo->estado == 1) echo "selected"; ?> > Activo </option>
                                                <option value="0" <?php if($this->metodo->estado == 0) echo "selected"; ?>>Inactivo</option>
                                            </select>
                                        </div>
                                        <button type="submit" class="btn btn-default">Submit Button</button>
                                        <button type="reset" class="btn btn-default">Reset Button</button>
                                    </form>
                                </div>
                                <!-- /.col-lg-6 (nested) -->
                                
                                <!-- /.col-lg-6 (nested) -->
                            </div>
                            <!-- /.row (nested) -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>