<div id="page-wrapper" style="min-height: 271px;">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Agregar Producto</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                           
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-lg-6">
                                    <form role="form" method="post" action="<?php echo BASE_URL ?>/backend/producto/agregarProducto"
                                          enctype="multipart/form-data">
                                        <div class="form-group">
                                            <label>Nombre</label>
                                            <input type='text' name='nombre' class="form-control"
                                                    value="">
                                            
                                        </div>
                                        <div class="form-group">
                                            <label>Descripción</label>
                                            <textarea name='descripcion' class="form-control" rows="3"></textarea>
                                        </div>
                                        <div class="form-group">
                                            <label>Resumen</label>
                                            <textarea name='resumen' class="form-control" rows="3"></textarea>
                                        </div>
                                        <div class="form-group">
                                            <label>Slug</label>
                                            <textarea name='slug' class="form-control" rows="3"></textarea>
                                        </div>
                                        <div class="form-group">
                                            <label>Sku</label>
                                            <textarea name='sku' class="form-control" rows="3"></textarea>
                                        </div>
                                        <div class="form-group">
                                            <label>Stock</label>
                                            <input type='text' name='stock' class="form-control"
                                                    value="">
                                            
                                        </div>
                                        <div class="form-group">
                                            <label>Precio de Costo</label>
                                            <input type='text' name='precio_costo' class="form-control"
                                                    value="">
                                            
                                        </div>
                                        <div class="form-group">
                                            <label>Precio de Venta</label>
                                            <input type='text' name='precio_venta' class="form-control"
                                                    value="">
                                            
                                        </div>
                                        <div class="form-group">
                                            <label>Categoría</label>
                                            <select name="categoria" id="categoria_id" class="form-control">
                                                <?php
                                                foreach ($this->categorias as $categoria) {
                                                  ?>
                                                   <option value="<?php echo $categoria['id']; ?>">
                                                       <?php echo $categoria['nombre']; ?></option>
                                                <?php     
                                                } 
                                                ?>
                                            </select>
                                            
                                        </div>
                                        
                                        <div class="form-group">
                                            <label class="control-label" for="imagen">Imagen</label> 
                                            <input type='file' id="inputIMAGEN" name='imagen' placeholder="">
                                        </div>
                                         <div class="form-group">
                                            <label>Estado</label>
                                            <select class="form-control" name="estado">
                                                <option value="1"> Activo </option>
                                                <option value="0">Inactivo</option>
                                            </select>
                                        </div>
                                        <button type="submit" class="btn btn-default">Submit Button</button>
                                        <button type="reset" class="btn btn-default">Reset Button</button>
                                    </form>
                                </div>
                                <!-- /.col-lg-6 (nested) -->
                                
                                <!-- /.col-lg-6 (nested) -->
                            </div>
                            <!-- /.row (nested) -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>

