<div id="page-wrapper" style="min-height: 271px;">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Detalle del Producto</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                           Generales
                        </div>
                        <div class="panel-body well well-lg">
                            <div class="row">
                                <div class="col-lg-6">
                                
                                    <div class="form-group">
                                        <label>Id de producto:</label><?php echo $this->producto->id ?><br>
                                        <label>Nombre:</label><?php echo $this->producto->nombre ?><br>
                                        <label>Descripción:</label><?php echo $this->producto->descripcion ?><br>
                                        <label>Resumen:</label><?php echo $this->producto->resumen ?><br>
                                        <label>Categoría Asociada:</label><?php echo $this->producto->categoria_nombre ?><br>
                                    </div>

                                </div>
                               
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <img src='<?php echo BASE_URL; ?>temp/productos/<?php echo $this->producto->source ?>'width='200px' height='200px' />
                                    </div>
                                </div>
                                
                                
                            </div>
                            <!-- /.row (nested) -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                           Atributos
                        </div>
                        <div class="panel-body well well-lg">
                            <div class="row">
                                <div class="col-lg-6">
                                
                                <div class="form-group">
                                    <label>SKU:</label><?php echo $this->producto->sku ?><br>
                                    <label>Stock:</label><?php echo $this->producto->stock ?><br>
                                    <label>Precio de Costo:</label><?php echo $this->producto->precio_costo ?><br>
                                    <label>Precio de Venta:</label><?php echo $this->producto->precio_venta ?><br>
                                    
                                </div>   
                                </div>
                                
                            </div>
                            <!-- /.row (nested) -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                           Otros
                        </div>
                        <div class="panel-body well well-lg">
                            <div class="row">
                                <div class="col-lg-6">
                                
                                <div class="form-group">
                                    <label>Slug del Producto:</label><?php echo $this->producto->slug ?><br>
                                    <label>Estado:</label><?php echo Util::getEstado($this->producto->estado); ?><br>
                                    <label>Fecha de Creación:</label><?php echo $this->producto->fecha_creacion ?><br>
                                    <label>Producto Borrado:</label><?php echo Util::getIsDeleted($this->producto->id); ?><br>
                                    
                                </div>   
                                </div>
                                
                            </div>
                            <!-- /.row (nested) -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>

