<head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">
        
        <link media="all" rel="stylesheet" type="text/css" href="<?php echo BASE_URL?>public/assets/frontend/css/style.css">
        <link media="all" rel="stylesheet" type="text/css" href="<?php echo BASE_URL?>public/assets/frontend/css/jquery.mCustomScrollbar.css">
        <link media="all" rel="stylesheet" type="text/css" href="<?php echo BASE_URL?>public/assets/frontend/css/jquery.bxslider.css">
        
        <style>
            #header div.header-top ul.nav-user li{
                background: #c10e0e;
            }
            #header div.header-top ul.nav-user li ul.logged-user-options li a:hover{
                background: #c10e0e;
            }
            #header div.header-bot ul.main-menu>li:hover{
                border-bottom: 2px solid #c10e0e;
            }
            #home #carousel .carousel-indicators li.active{
                border: 1px solid #c10e0e;
                background: #c10e0e;
            }
            #home #featured-products li p.product-new-price{
                color: #c10e0e;
            }
            #header div.header-top{
                border-top: 3px solid #c10e0e;
            }
            @media only screen and (max-width: 1023px){
                
            }
            @media only screen and (max-width: 767px){
                
                #header div.header-top ul.nav-user li.unknown-user{
                    background: #c10e0e;
                }
                #header div.header-bot ul.main-menu{
                    background: #c10e0e;
                }
            }
            @media only screen and (max-width: 479px){

            }
        </style>
        <script type="text/javascript">
            var globalColor = "c10e0e";
        </script>
    </head>
<!--MY CART MODAL-->
            <div class="modal fade" id="my_cart_modal" tabindex="-1" role="dialog" aria-labelledby="my_cart_label" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            
                            <h4 class="modal-title" id="my_cart_label">Carrito de Compras</h4>
                        </div>
                        <div class="modal-body">
                            <table>
                                <tr class="my-cart-header">
                                    <th class="cart-item">Item</th>
                                    <th class="cart-detail">Nombre</th>
                                    <th class="cart-price">Precio</th>
                                    <th class="cart-quantity">Cantidad</th>
                                    <th class="cart-subtotal">Subtotal</th>
                                    <th class="cart-remove">Opciones</th>
                                </tr>
                                <?php foreach ($this->arrayCarro as $productCode => $producto): ?>
                                    <tr class="my-cart-body">
                                        <td class="cart-item">
                                            <img src="<?php echo BASE_URL; ?>temp/productos/<?php echo $producto['source']; ?>" width='50px' height='50px'>
                                        </td>
                                        <td class="cart-detail">
                                            <strong><?php echo $producto['nombre']?></strong>
                                            <p><?php echo $producto['nombre']?></p>
                                        </td>
                                        <td class="cart-price">
                                            <p>S/.<?php echo $producto['precio']?>.00</p>
                                        </td>
                                        <td class="cart-quantity">
                                           <p><?php echo $producto['cantidad']?></p>
                                        </td>
                                        <td class="cart-subtotal">
                                            S/. <?php echo $producto['importe']?>.00
                                        </td>
                                        <td class="">
                                          <!--  <a href="<?php echo BASE_URL;?>carro/carro/<?php echo $this->producto;?>/add">+</a>
                                            <a href="<?php echo BASE_URL;?>carro/carro/<?php echo $this->producto;?>/remove">-</a> -->
                                            <a href="<?php echo BASE_URL;?>carro/carro/<?php echo $this->producto;?>/removeProd">Eliminar</a>
                                        </td>

                                    </tr>
                                <?php endforeach; ?>
                                <tr class="my-cart-footer">
                                    <td class="cart-total" colspan="6">
                                        S/.<?php echo $this->importetotal?>.00
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div class="modal-footer">
                            <ul>
                                <li class="payment-visa"></li>
                                <li class="payment-mastercard"></li>
                                <li class="payment-ae"></li>
                                <li class="payment-contraentrega"></li>
                                <li class="payment-pago-efectivo"></li>
                            </ul>
                            <button type="button" class="buy"><a href="<?php echo BASE_URL;?>carro/comprar">Comprar</a></button>
                            
                            <button type="button" class="keep-buying" data-dismiss="modal"><a href="<?php echo BASE_URL;?>producto/detalle/<?php echo $this->producto; ?>">Seguir Comprando</a></button>
                        </div>
                    </div>
                </div>
            </div>
<script type="text/javascript" src="<?php echo BASE_URL; ?>public/assets/frontend/js/jquery-1.8.3.min.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL; ?>public/assets/frontend/js/functions.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL; ?>public/assets/frontend/js/bootstrap.min.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL; ?>public/assets/frontend/js/jquery.mCustomScrollbar.concat.min.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL; ?>public/assets/frontend/js/jquery.elevateZoom.min.js"></script>
<script type="text/javascript" src="<?php echo BASE_URL; ?>public/assets/frontend/js/jquery.bxslider.js"></script>
<script>
