<div id="page-wrapper" style="min-height: 271px;">
            <div class="row">
                <div class="col-lg-12">
                    <h2 class="page-header">Detalle del Pedido</h2>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-primary">
                        
                        <div class="panel-heading">
                           Generales
                        </div>
                        <div class="panel-body well well-lg">
                            <div class="row">
                                <div class="col-lg-6">
                                    <label>N° de pedido: </label><?php echo $this->pedido->id?><br>
                                    <label>Método de Pago: </label><?php echo $this->pedido->metodo_nombre?><br>
                                    <label>Sub Total: </label><?php echo $this->pedido->subtotal?><br>
                                    <label>Costo de Envío: </label><?php echo $this->pedido->costo_envio?><br>
                                    <label>Total: </label><?php echo $this->pedido->total?><br>
                                    <label>Fecha de Compra : </label><?php echo $this->pedido->fecha_creacion?>
                                </div>
                                <!-- /.col-lg-6 (nested) -->
                                
                                <!-- /.col-lg-6 (nested) -->
                            </div>
                            
                            
                            
                            <!--<div class="row">
                                <h3>Estado del Pedido</h3>
                                <div class="col-lg-6">
                                    
                                </div> -->
                                <!-- /.col-lg-6 (nested) -->
                                
                                <!-- /.col-lg-6 (nested) -->
                            </div>
                            <!-- /.row (nested) -->
                        </div>
                    
                    <div class="panel panel-primary">
                        
                        <div class="panel-heading">
                          Usuario
                        </div>
                        <div class="panel-body well well-lg">
                            
                            <div class="row">
                                
                                <div class="col-lg-6">
                                    <label>Nombres y Apellidos: </label><?php echo $this->pedido->usuario_nombre." ".$this->pedido->usuario_apellido?><br>
                                    <label>Correo: </label><?php echo $this->pedido->usuario_email?><br>
                                    <label>DNI: </label><?php echo $this->pedido->dni?><br>
                                    <label>Teléfono: </label><?php echo $this->pedido->telefono?><br>
                                    <label>Dirección: </label><?php echo $this->pedido->direccion?><br>
                                    <label>Referencia: </label><?php echo $this->pedido->referencia?>
                                </div>
                                <!-- /.col-lg-6 (nested) -->
                                
                                <!-- /.col-lg-6 (nested) -->
                            </div>
                            
                            
                            <!--<div class="row">
                                <h3>Estado del Pedido</h3>
                                <div class="col-lg-6">
                                    
                                </div> -->
                                <!-- /.col-lg-6 (nested) -->
                                
                                <!-- /.col-lg-6 (nested) -->
                            </div>
                            <!-- /.row (nested) -->
                        </div>
                    
                    <div class="panel panel-primary">
                        
                        <div class="panel-heading">
                           Productos
                        </div>
                        <div class="panel-body">
                            
                            <div class="row">
                               
                                <?php $contador = 1;?>
                                <?php while($reg = $this->items->fetch_object()):?>
                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                       <?php echo "Producto ".$contador?>  
                                    </div>
                                    <div class="panel-body">
                                        <div class="col-lg-6">
                                                <label>SKU: </label><?php echo $reg->item_sku ?><br>
                                                <label>Nombre: </label><?php echo $reg->item_nombre ?><br>
                                                <label>Cantidad: </label><?php echo $reg->item_cantidad ?><br>
                                                <label>Precio Unitario: </label><?php echo $reg->item_precio_unit ?><br>
                                                <label>Total: </label><?php echo $reg->item_cantidad * $reg->item_precio_unit ?><br>
                                        </div>
                                        <div class="col-lg-6">
                                            <img src="<?php echo BASE_URL; ?>temp/productos/<?php echo $reg->item_source ?>" width='100px' height='100px'>
                                        </div>
                                    </div>
                                </div>
                                
                                <?php $contador++?>
                                <?php endwhile ;?>
                                <!-- /.col-lg-6 (nested) -->
                                
                                <!-- /.col-lg-6 (nested) -->
                            </div>
                            
                            
                            <!--<div class="row">
                                <h3>Estado del Pedido</h3>
                                <div class="col-lg-6">
                                    
                                </div> -->
                                <!-- /.col-lg-6 (nested) -->
                                
                                <!-- /.col-lg-6 (nested) -->
                            </div>
                            <!-- /.row (nested) -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>

